export type Customer = {
  id: string;
  tenantId: string;
  personType: "pf" | "pj";
  name: string;
  legalName: string | null;
  tradeName: string | null;
  document: string | null;
  secondaryDocument: string | null;
  email: string | null;
  phone: string | null;
  whatsapp: string | null;
  ramal: string | null;
  postalCode: string | null;
  street: string | null;
  number: string | null;
  complement: string | null;
  neighborhood: string | null;
  city: string | null;
  state: string | null;
  status: "lead" | "active" | "inactive";
  source: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CustomerPayload = {
  personType: "pf" | "pj";
  name: string;
  legalName?: string;
  tradeName?: string;
  document?: string;
  secondaryDocument?: string;
  email?: string;
  phone?: string;
  whatsapp?: string;
  ramal?: string;
  postalCode?: string;
  street?: string;
  number?: string;
  complement?: string;
  neighborhood?: string;
  city?: string;
  state?: string;
  status?: "lead" | "active" | "inactive";
  source?: string;
  notes?: string;
};
